apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-imperative-config
  name: nginx-imperative-config
  namespace: dubovikov
spec:
  containers:
  - image: nginx
    name: nginx-imperative-config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
