# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.synced_folder "./ssl", "/vagrant/ssl"


  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.provision "shell", path: "scripts/server.sh", env: {"DOMAIN_NAME" => "lev.local"}
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.11"
    client.vm.provision "shell", path: "scripts/client.sh", env: {"DOMAIN_NAME" => "lev.local", "SERVER_IP" => "192.168.56.10"}
  end
end
