apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    app: mysql
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: mysql
    protocol: TCP
  selector:
    app: mysql
    release: {{ .Release.Name }}
