apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  labels:
    app: wordpress
    release: {{ .Release.Name }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | b64enc }}
  mysql-password: {{ .Values.secrets.mysqlPassword | b64enc }}
  wordpress-password: {{ .Values.secrets.wordpressPassword | b64enc }}
