{{- if .Values.wordpress.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.wordpress.persistence.storageClass }}
  storageClassName: {{ .Values.wordpress.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
{{- end }}
