# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  shared_dir = File.join(File.dirname(__FILE__), "shared")

  FileUtils.mkdir_p(shared_dir) unless File.directory?(shared_dir)

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "lesson6-server"
      vb.memory = "1024"
      vb.cpus = 2
    end

    server.vm.synced_folder shared_dir, "/shared"

    server.vm.provision "shell", path: "server-setup.sh"
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.11"

    client.vm.provider "virtualbox" do |vb|
      vb.name = "lesson6-client"
      vb.memory = "1024"
      vb.cpus = 2
    end

    client.vm.synced_folder shared_dir, "/shared"

    client.vm.provision "shell", path: "client-setup.sh"
  end
end
