# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "server" do |server|
    server.vm.box = "generic/ubuntu2204"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "lesson6-server"
      vb.memory = "512"
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "server-setup.sh"
  end

  config.vm.define "client" do |client|
    client.vm.box = "generic/ubuntu2204"
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.11"

    client.vm.provider "virtualbox" do |vb|
      vb.name = "lesson6-client"
      vb.memory = "512"
      vb.cpus = 1
    end

    client.vm.provision "shell", path: "client-setup.sh"
  end
end