# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = false

  # Dev environment
  config.vm.define "dev" do |node|
    node.vm.hostname = "dev"
    node.vm.network "private_network", ip: "192.168.56.10"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "lesson12-dev"
      vb.memory = "512"
    end
  end

  # Prod environment
  config.vm.define "prod" do |node|
    node.vm.hostname = "prod"
    node.vm.network "private_network", ip: "192.168.56.20"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "lesson12-prod"
      vb.memory = "512"
    end
  end

  # Общая подготовка для обеих ВМ
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip
  SHELL
end
