apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-mysql-0
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
