{
 "title": "Reddit App Monitoring",
 "panels": [
  {
   "title": "Requests to /",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(probe_duration_seconds_count{instance=~'.*/'}[5m]))"
    }
   ]
  },
  {
   "title": "Requests to /new",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(probe_duration_seconds_count{instance=~'.*/new'}[5m]))"
    }
   ]
  },
  {
   "title": "90th Percentile Response Time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(probe_duration_seconds_bucket[5m]))"
    }
   ]
  }
 ]
}