Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.hostname = "server"

    server.vm.provider "virtualbox" do |vb|
      vb.cpus = 4
      vb.memory = 2048
    end
  end

  config.vm.define "store" do |store|
    store.vm.box = "ubuntu/jammy64"
    store.vm.network "private_network", ip: "192.168.56.11"
    store.vm.hostname = "store"

    store.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 2048
    end
  end
end
